name: cmist
dependencies:
  - python=3.8
  - numpy
  - scipy
  - matplotlib
  - ipython
  - pandas
  - selenium
  - xarray
  - pip
  - pip:
    - git+https://github.com/wesleybowman/UTide.git@master#egg=UTide
